# Generated by Django 3.1.1 on 2021-02-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(default='user.png', upload_to=''),
        ),
    ]
