# Generated by Django 3.1.1 on 2021-03-19 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mylife', '0011_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='usuario_creador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='del_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='usuario_invitado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='al_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
