# Generated by Django 3.1.1 on 2021-03-20 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0012_auto_20210318_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='fecha_creacion',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='room',
            name='usuario_creador',
        ),
        migrations.RemoveField(
            model_name='room',
            name='usuario_invitado',
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_message', to='mylife.room'),
        ),
    ]
