# Generated by Django 3.1.1 on 2021-03-20 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mylife', '0013_auto_20210320_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(related_name='users_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
