# Generated by Django 3.1.1 on 2021-08-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0016_auto_20210813_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='estado_conexion',
            field=models.CharField(choices=[('Conectado', 'Conectado'), ('Ausente', 'Ausente'), ('Desconectado', 'Desconectado')], default='Conectado', max_length=50, null=True),
        ),
    ]
